# This file is intended to automatize the testing of SimGrid on
# Windows using the appveyor.com continuous integration service

os: Visual Studio 2015
version: "{build}"
clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
- cmake --version
- msbuild /version
- git config --global core.longpaths true
- git config --global core.autocrlf input

environment:
  global:
    BOOST_ROOT: c:\Libraries\boost_1_59_0
    BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\stage\lib
    #  BOOST_ROOT: c:\Libraries\boost
    #  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

  matrix:
    - COMPILER: MinGW-w64

#    - COMPILER: MSVC15
#      PLATFORM: Win32
#    - COMPILER: MSVC15
#      PLATFORM: x64
      
install:
- if [%COMPILER%]==[MinGW]     set PATH=C:\MinGW\bin;%PATH%
- if [%COMPILER%]==[MinGW]     mingw-get update
- if [%COMPILER%]==[MinGW]     rename "C:\Program Files (x86)\Git\bin\sh.exe" "sh2.exe"
- if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw64\bin;%PATH%
- if [%COMPILER%]==[MinGW-w64] rename "C:\Program Files (x86)\Git\bin\sh.exe" "sh2.exe"
- if [%COMPILER%]==[MinGW-w64] appveyor DownloadFile "https://raw.githubusercontent.com/symengine/dependencies/5cff7d1736877336cf9fb58267111beea4fa152f/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z" -FileName mw64.7z
- if [%COMPILER%]==[MinGW-w64] 7z x -oC:\ mw64.7z > NUL
- if [%COMPILER%]==[MSYS2]     set PATH=C:\msys64\bin,%PATH%

build_script:
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 14 2015"       -Denable_java=ON -Denable_smpi=OFF -Denable_mallocators=OFF .
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64]   cmake -G "Visual Studio 14 2015 Win64" -Denable_java=ON -Denable_smpi=OFF -Denable_mallocators=OFF .
- if not [%COMPILER%]==[MSVC15]                      cmake -G "MinGW Makefiles"             -Denable_java=ON -Denable_smpi=OFF -Denable_mallocators=OFF -Denable_lto=OFF .
- if [%COMPILER%]==[MSVC15]     msbuild ALL_BUILD.vcxproj /verbosity:normal
- if not [%COMPILER%]==[MSVC15] mingw32-make VERBOSE=1
- cd C:/projects/simgrid/examples/java && java -classpath ".;../../simgrid.jar" masterslave.Masterslave ../platforms/platform.xml masterslave/masterslaveDeployment.xml || true

test_script:
- C:/projects/simgrid && ctest --output-on-failure || true

artifacts:
- path: simgrid.jar
  name: jarfile

# notifications:
# - irc: "irc.debian.org#simgrid" # Not implemented by AppVeyor yet :(
# Some source of inspiration:

# https://github.com/sympy/symengine/blob/master/appveyor.yml <- MS, mingw & mingw64

# https://github.com/dartsim/dart/blob/master/appveyor.yml
# https://github.com/osmcode/libosmium/blob/master/appveyor.yml
# https://github.com/polysquare/cmake-unit/blob/master/appveyor.yml
# https://github.com/openvswitch/ovs/blob/master/appveyor.yml

# https://github.com/behdad/harfbuzz/pull/112/files