# This file is intended to automatize the testing of SimGrid on
# Windows using the appveyor.com continuous integration service

os: Visual Studio 2015
version: "{build}"
clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
- cmake --version
- msbuild /version
- git config --global core.longpaths true
- git config --global core.autocrlf input

platform: 
  - Win32 # This is Windows 32bits
#  - x64   # This is Windows 64bits

environment:
  BOOST_ROOT: c:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\stage\lib
#  BOOST_ROOT: c:\Libraries\boost
#  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib
  
build_script:
- if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 14 2015"     -Denable_smpi=OFF -Denable_mallocators=OFF .
- if [%PLATFORM%]==[x64] cmake -G "Visual Studio 14 2015 Win64" -Denable_smpi=OFF -Denable_mallocators=OFF .
- msbuild ALL_BUILD.vcxproj /verbosity:normal

test_script:
- ctest --output-on-failure

# notifications:
# - irc: "irc.debian.org#simgrid" # Not implemented by AppVeyor yet :(
# Some source of inspiration:

# https://github.com/sympy/symengine/blob/master/appveyor.yml <- MS, mingw & mingw64

# https://github.com/dartsim/dart/blob/master/appveyor.yml
# https://github.com/osmcode/libosmium/blob/master/appveyor.yml
# https://github.com/polysquare/cmake-unit/blob/master/appveyor.yml
# https://github.com/openvswitch/ovs/blob/master/appveyor.yml

# https://github.com/behdad/harfbuzz/pull/112/files