# This file is intended to automatize the testing of SimGrid on
# Windows using the appveyor.com continuous integration service

os: Visual Studio 2015
version: "{build}"
clone_depth: 1

platform: 
  - Win32 # This is Windows 32bits (don't activate since we dont compile properly anyway)
#  - x64   # This is Windows 64bits

environment:
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

build_script:
- if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 14 2015"  -DCMAKE_CXX_FLAGS_RELEASE="/MT /W1 /O2 /Ob2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 /W1" .
- if [%PLATFORM%]==[x64] cmake -G "Visual Studio 14 2015 Win64"  -DCMAKE_CXX_FLAGS_RELEASE="/MT /W1 /O2 /Ob2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 /W1" .
- msbuild ALL_BUILD.vcxproj /verbosity:normal

test_script:
- ctest --output-on-failure

# notifications:
# - irc: "irc.debian.org#simgrid" # Not implemented by AppVeyor yet :(
# Some source of inspiration:

# https://github.com/sympy/symengine/blob/master/appveyor.yml <- MS, mingw & mingw64

# https://github.com/dartsim/dart/blob/master/appveyor.yml
# https://github.com/osmcode/libosmium/blob/master/appveyor.yml
# https://github.com/polysquare/cmake-unit/blob/master/appveyor.yml
# https://github.com/openvswitch/ovs/blob/master/appveyor.yml

# https://github.com/behdad/harfbuzz/pull/112/files