# This file is intended to automatize the testing of SimGrid on
# Windows using the appveyor.com continuous integration service

os: MinGW
version: "{build}"
clone_depth: 1

platform: 
  - Win32 # This is Windows 32bits (don't activate since we dont compile properly anyway)
#  - x64   # This is Windows 64bits

environment:
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib
  MSYS2_BASEVER: 20150512
  MSYS2_ARCH: x86_64

install:
- appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/%MSYS2_ARCH%/msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz" -FileName "msys2.tar.xz"
- 7z x msys2.tar.xz
- 7z x msys2.tar > NUL
- msys64\usr\bin\bash -lc ""
- msys64\usr\bin\bash -lc "for i in {1..3}; do pacman --noconfirm -Suy gcc make cmake perl && break || sleep 15; done" 
#- set PATH=C:\mingw64\bin;%PATH%
#- set CC=gcc

build_script:
- msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; PATH=$PATH:/mingw64/bin:/mingw32/bin; cmake -G \"MSYS Makefiles\" -DBOOST_ROOT=\"%BOOST_ROOT%\" -DBOOST_LIBRARYDIR=\"%BOOST_LIBRARYDIR%\" -DBoost_USE_STATIC_LIBS=ON -Denable_debug=ON -Denable_documentation=OFF -Denable_coverage=OFF -Denable_tracing=ON -Denable_java=OFF -Denable_model-checking=OFF ."
- msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; echo XXX simgrid_config.h; cat include/simgrid_config.h"
- msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; echo XXX src/internal_config.h; cat src/internal_config.h"
- msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; PATH=$PATH:/mingw64/bin:/mingw32/bin; make VERBOSE=1"

test_script:
- msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; PATH=$PATH:/mingw64/bin:/mingw32/bin; ctest -VV"

# notifications:
# - irc: "irc.debian.org#simgrid" # Not implemented by AppVeyor yet :(
# Some source of inspiration:
# https://github.com/dartsim/dart/blob/master/appveyor.yml
# https://github.com/osmcode/libosmium/blob/master/appveyor.yml
# https://github.com/polysquare/cmake-unit/blob/master/appveyor.yml
# https://github.com/openvswitch/ovs/blob/master/appveyor.yml

# https://github.com/behdad/harfbuzz/pull/112/files