# This file is intended to automatize the testing of SimGrid on
# Windows using the appveyor.com continuous integration service

version: "{build}"
clone_depth: 1

platform: 
  - Win32 # This is Windows 32bits (don't activate since we dont compile properly anyway)
#  - x64   # This is Windows 64bits

environment:
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib
    
build_script:
- '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd"'
- C:\MinGW\msys\1.0\bin\bash -lc "echo \"C:/MinGW /mingw\" > /etc/fstab"
- C:\MinGW\msys\1.0\bin\bash -lc "printenv"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/projects/simgrid && cmake -G \"MSYS Makefiles\" -DBOOST_ROOT=\"%BOOST_ROOT%\" -DBOOST_LIBRARYDIR=\"%BOOST_LIBRARYDIR%\" -DBoost_USE_STATIC_LIBS=ON -Denable_debug=ON -Denable_documentation=OFF -Denable_coverage=OFF -Denable_tracing=ON -Denable_java=OFF -Denable_model-checking=OFF ."
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/projects/simgrid; echo XXX simgrid_config.h; cat include/simgrid_config.h"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/projects/simgrid; echo XXX src/internal_config.h; cat src/internal_config.h"
#- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/projects/simgrid; echo XXX Internal builtins; gcc -dM -E - < /dev/null"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/projects/simgrid && make VERBOSE=1"

test_script:
  cmd: ctest -VV

# notifications:
# - irc: "irc.debian.org#simgrid" # Not implemented by AppVeyor yet :(
# Some source of inspiration:
# https://github.com/dartsim/dart/blob/master/appveyor.yml
# https://github.com/osmcode/libosmium/blob/master/appveyor.yml
# https://github.com/polysquare/cmake-unit/blob/master/appveyor.yml
# https://github.com/openvswitch/ovs/blob/master/appveyor.yml
